//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetStalker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetStalker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information contained on NetStalker Desktop app (the &quot;Service&quot;) is for general information purposes only.
        ///
        ///I (The developer) assumes no responsibility for errors or omissions in the contents on the Service.
        ///
        ///In no event I shall be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other sort, arising out of or in connection with the use of the Service or the contents of the Service.
        ///
        ///I can not wa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit the application ?.
        /// </summary>
        internal static string AppQuit {
            get {
                return ResourceManager.GetString("AppQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap color_cancel {
            get {
                object obj = ResourceManager.GetObject("color_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap color_error {
            get {
                object obj = ResourceManager.GetObject("color_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap color_help {
            get {
                object obj = ResourceManager.GetObject("color_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap color_info {
            get {
                object obj = ResourceManager.GetObject("color_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap color_ok {
            get {
                object obj = ResourceManager.GetObject("color_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected device was not found in the list or targets.
        /// </summary>
        internal static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be longer than 20 characters!.
        /// </summary>
        internal static string FriendlyNameCharLimit {
            get {
                return ResourceManager.GetString("FriendlyNameCharLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Name cannot be empty!.
        /// </summary>
        internal static string FriendlyNameEmpty {
            get {
                return ResourceManager.GetString("FriendlyNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoof Protection occurs whenever a blocking or a redirection operation is active.
        ///It protects you pc from being blocked or redirected by the same tool
        ///or any other spoofing software..
        /// </summary>
        internal static string HelpBubble {
            get {
                return ResourceManager.GetString("HelpBubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some guidelines on how to use this software properly:
        ///
        ///1- In order to use the Packet Sniffer you have to activate redirection for the selected device first. Note: For the Packet Sniffer to work properly, redirection and speed limitation will be deactivated for all but the selected device.
        ///2- In order to use the Speed Limiter you have to activate redirection for the selected device, once activated it will start redirecting packets for the selected device with no speed limitation, then you can open the spe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_ok_red {
            get {
                object obj = ResourceManager.GetObject("icons8_ok_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a device first and activate redirection for it!.
        /// </summary>
        internal static string LimiterDeviceNotReady {
            get {
                return ResourceManager.GetString("LimiterDeviceNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirection must be active for this device!.
        /// </summary>
        internal static string MustRedirectFirst {
            get {
                return ResourceManager.GetString("MustRedirectFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new device detected!.
        /// </summary>
        internal static string NewTargetNotificationPrompt {
            get {
                return ResourceManager.GetString("NewTargetNotificationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can not target the gateway or your own ip address!.
        /// </summary>
        internal static string NoGatewayOrOwnDevice {
            get {
                return ResourceManager.GetString("NoGatewayOrOwnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Speed Limiter can&apos;t be used while the sniffer is active!.
        /// </summary>
        internal static string NoLimiterWhileSniffer {
            get {
                return ResourceManager.GetString("NoLimiterWhileSniffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want me to inform you of newly connected devices?
        ///(This option can be changed back in the options menu).
        /// </summary>
        internal static string NotificationsPrompt {
            get {
                return ResourceManager.GetString("NotificationsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed!.
        /// </summary>
        internal static string OpFailed {
            get {
                return ResourceManager.GetString("OpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to do a refresh, the scanner must be active and no other operations are in progress..
        /// </summary>
        internal static string RefreshScanNotActive {
            get {
                return ResourceManager.GetString("RefreshScanNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scan is still in progress, please wait until its finished..
        /// </summary>
        internal static string ScanStillInProgress {
            get {
                return ResourceManager.GetString("ScanStillInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a device first!.
        /// </summary>
        internal static string SelectDevice {
            get {
                return ResourceManager.GetString("SelectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1- In order to begin capturing packets click on START.
        ///2- You can clear the list from items by pressing CLEAR.
        ///3- You can save the captured packets in a form of a log file by stopping the ongoing operation, pressing EXPORT and choosing a location for the file to be saved.
        ///4- In order to open a chosen packet do a right click on the selected packet and click \&quot;Show Packet\&quot; and it will be displayed in the packet viewer on the bottom left of the window.
        ///5- To resolve the destination ip in HTTPS Packets jus [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SnifferHelp {
            get {
                return ResourceManager.GetString("SnifferHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Packet Sniffer can&apos;t be used while the limiter is active!.
        /// </summary>
        internal static string SnifferLimiterStillActive {
            get {
                return ResourceManager.GetString("SnifferLimiterStillActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spinB {
            get {
                object obj = ResourceManager.GetObject("spinB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spinW {
            get {
                object obj = ResourceManager.GetObject("spinW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
